---
name: NuGet

on:
  push:
    branches:
      - deploy

env:
  BUILD_CONFIGURATION: 'Release'

jobs:
  publish:
    name: Publish on NuGet
    runs-on: windows-latest
    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0

      - name: â¬‡ï¸ Checkout repository
        uses: actions/checkout@v2

      - name: ğŸš§ Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x

      - name: ğŸ“¦ Build the project
        run: |
          cd src/Hackedb/
          dotnet restore
          dotnet build --configuration '${{ env.BUILD_CONFIGURATION }}'
          dotnet pack -c '${{ env.BUILD_CONFIGURATION }}'

      - name: ğŸ” Publish to nuget.org
        uses: brandedoutcast/publish-nuget@v2.5.2
        with:
          PROJECT_FILE_PATH: src/Hackedb/Hackedb.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
